### PR TITLE
remove mention to map

### PR DESCRIPTION
**Pull request by felquis**
since it doesn't work with 4.13.4

while reading the doc, and following everything to learn express. I found the `app.map` method, isn't defined anymore.. error

``` txt
app.map({
    ^

TypeError: app.map is not a function
    at Object.<anonymous> (/Users/felquis/Documents/projects/learn-expressjs/app.js:86:5)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

code examples from https://github.com/expressjs/express/blob/4.13.1/examples/route-map/index.js#L28-L66

using "express": "^4.13.4"

### CODE REVIEW

**Comment by dougwilson** [comment]
Hi @felquis, you have to actually run the example. The example creates `app.map` right above what you linked to: https://github.com/expressjs/express/blob/4.13.1/examples/route-map/index.js#L11-L26

**Comment by felquis** [comment]
oh god

**Comment by dougwilson** [comment]
The purpose of the example is to show how one could go about implementing a `app.map` sugar API on top of API (i.e. how to extend Express.js).
